# Generated by Django 5.0.1 on 2024-01-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('descripcion', models.CharField(max_length=50)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('descripcion', models.CharField(max_length=50)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('descripcion', models.CharField(max_length=50)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('descripcion', models.CharField(max_length=50)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=255)),
                ('descripcion', models.CharField(default=None, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('fk_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto_app.categoria')),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
                ('fk_marca', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto_app.marca')),
                ('fk_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto_app.proveedor')),
                ('fk_sub_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto_app.sub_categoria')),
            ],
        ),
    ]
