# Generated by Django 5.0.1 on 2024-01-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0002_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fk_sub_categoria',
        ),
        migrations.DeleteModel(
            name='Sub_categoria',
        ),
    ]
