# Generated by Django 5.0.1 on 2024-01-31 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0003_remove_producto_fk_sub_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
