# Generated by Django 5.0.1 on 2024-02-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0004_remove_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
