# Generated by Django 5.0.1 on 2024-01-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200)),
                ('apellido', models.CharField(default=None, max_length=200)),
                ('cedula', models.CharField(default=None, max_length=10)),
                ('correo', models.CharField(default=None, max_length=200)),
                ('edad', models.PositiveIntegerField(default=None)),
                ('celular', models.CharField(default=None, max_length=15)),
                ('fk_estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estado_app.estado')),
            ],
        ),
    ]
